[package]
name = "chat_bot_sample"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chatbot = "0.2.3"
openssl = "0.9.23"
openssl-sys = "0.9.36"
slack = "0.25.0"
